return {
    Text = "󰦨",
    Method = "",
    Function = "󰡱",
    Constructor = "󰦑",
    Field = "󰽐",
    Variable = "󰫧",
    Class = "",
    Interface = "󱜤",
    Module = "󰕳",
    Property = "",
    Unit = "󰭍",
    Value = "󰲖",
    Enum = "󰒠",
    Keyword = "",
    Snippet = "󰑖",
    Color = "",
    File = "󰈮",
    Refrence = "",
    Folder = "",
    EnumMember = "󰡀",
    Constant = "󰏿",
    Struct = "󰠡",
    Event = "",
    Operator = "󰊴",
    TypeParameter = ""
}
